version: "3.8"

services:
  api:
    container_name: ivao-rfe-api
    build:
      context: ./docker
    ports:
      - 80:80
    volumes:
      - ./backend:/var/www/app
    links:
      - db
  front:
    container_name: ivao-rfe-front
    build:
      context: ./
      dockerfile: ./docker/front/Dockerfile
    volumes:
      - ./frontend:/var/www/app
    links:
      - db
      - api
    ports:
      - 3000:3000
  db:
    container_name: ivao-rfe-db
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./docker/web/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
