version: "3.3"

services:
  api:
    container_name: booking-api
    build:
      context: ./docker
    ports:
      - 80:80
    volumes:
      - ./backend:/var/www/app
    links:
      - db
  db:
    container_name: booking-db
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./docker/web/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
  phpmyadmin:
    container_name: booking-phpmyadmin
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=secret
