on: push
name: Build and Publish Front End Framework Website
jobs:
  FRONTEND:
    name: Frontend
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Build Project
        run: |
          cd frontend
          yarn install
          yarn build

      - name: FTP-Deploy-Action
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_username: ${{ secrets.FTP_USER }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "./frontend/build"
          exclude: "node_modules"
          dist_target_dir: "./public_html/booking.br.ivao.aero"
  ADMIN:
    name: Admin
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Build Project
        run: |
          cd admin
          yarn install
          yarn build

      - name: FTP-Deploy-Action
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_username: ${{ secrets.FTP_USER }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "./admin/build"
          exclude: "node_modules"
          dist_target_dir: "./public_html/booking.br.ivao.aero/admin"

  BACKEND:
    name: Backend
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: FTP-Deploy-Action
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_username: ${{ secrets.FTP_USER }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "./backend"
          exclude: "node_modules"
          dist_target_dir: "./public_html/booking.br.ivao.aero/api"
